version: '3.4'
services:
    mysql:
      ports:
        - "3306:3306"
      expose:
      # Opens port 3306 on the container
        - '3306'
      volumes:
        - db-volume:/var/lib/meusql
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: IBMChallenge@2024
        MYSQL_USER: root
        MYSQL_PASSWORD: IBMChallenge@2024
        MYSQL_DATABASE: ibmchallenge
 
    phpmyadmin:
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=root
      links:
        - mysql
      restart: always
 
volumes:
  db-volume: